export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';


export const GETCHAMBRES='GETCHAMBRES';
export const GETCHAMBRES_SUCCESS='GETCHAMBRES_SUCCESS';
export const GETCHAMBRES_FAIL='GETCHAMBRES_FAIL';
export const GETONECHAMBRE='GETONECHAMBRE';
export const ADDCHAMBRES='ADDCHAMBRES';
export const DELETECHAMBRES='DELETECHAMBRES';
export const EDITCHAMBRES='EDITCHAMBRES';